#!/bin/tcsh -f

if ( "$1" == "-h" || "$1" == "--help" || "$1" == "" ) then
  echo
  echo "greps: searches CoastGuard source code for regular expression"
  echo
  echo "usage:"
  echo "  greps <regex>"
  echo
  exit
endif

ack-grep --help >& /dev/null
if ( "$?" == "0" ) then
  set GREP_COMMAND=ack-grep
else
  ack --help >& /dev/null
  if ( "$?" == "0" ) then
    set GREP_COMMAND=ack
  else
    set GREP_COMMAND=grep
  endif
endif

$GREP_COMMAND "$*" `find coast_guard -name "*.py"`

$GREP_COMMAND "$*" `find configurations -name "*.cfg"`

$GREP_COMMAND "$*" `find rcvr_files -name "*.txt"`

$GREP_COMMAND "$*" `find scripts -name "*.sh"`
